# Generated by Django 5.2.1 on 2025-06-14 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investmentwithdrawal'),
        ('main', '0007_deposit_related_package_alter_deposit_proof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_investment', to='main.deposit'),
        ),
    ]
