# Generated by Django 5.2.1 on 2025-06-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_transaction_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction_pin',
        ),
    ]
