# Generated by Django 5.2.1 on 2025-06-14 03:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='static/default_field.png', max_length=255, verbose_name='profile_pics/'),
        ),
    ]
