# Generated by Django 5.2.1 on 2025-08-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transactionpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('nationality', models.CharField(default='USA', max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(choices=[('passport', 'U.S. Passport'), ('ssn', 'Social Security Number'), ('state_id', 'State ID'), ('driver_license', 'Driver’s License'), ('greencard', 'Green Card')], max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='kyc/id_documents/')),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/')),
                ('proof_of_address', models.ImageField(blank=True, null=True, upload_to='kyc/proof_of_address/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
            },
        ),
    ]
