# Generated by Django 5.2.1 on 2025-06-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank', 'Bank Transfer'), ('cashapp', 'Cash App'), ('crypto', 'Crypto')], max_length=20)),
                ('label', models.CharField(help_text='e.g. BTC Wallet 1, CashApp Tag 2', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crypto_type', models.CharField(blank=True, max_length=20, null=True)),
                ('crypto_address', models.CharField(blank=True, max_length=200, null=True)),
                ('cashapp_tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Deposit Destination',
                'verbose_name_plural': 'Deposit Destinations',
            },
        ),
    ]
