# Generated by Django 5.2.1 on 2025-06-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_depositaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank', 'Bank Transfer'), ('giftcard', 'Gift Card'), ('cashapp', 'Cash App'), ('crypto', 'Crypto')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('unavailable', 'Unavailable')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='deposit_proofs/')),
                ('giftcard_pin', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='main.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
