# Generated by Django 5.2.1 on 2025-06-11 21:06

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='proof_image',
            field=cloudinary.models.CloudinaryField(default='static/default_field.png', max_length=255, verbose_name='deposit_proofs/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
