# Generated by Django 5.2.1 on 2025-06-12 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
