# Generated by Django 5.2.1 on 2025-06-14 03:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investmentwithdrawal'),
        ('main', '0006_alter_deposit_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='related_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='investments.investmentpackage'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='proof_image',
            field=cloudinary.models.CloudinaryField(default='static/default_field.png', max_length=255, verbose_name='deposit_proofs/'),
        ),
    ]
