# Generated by Django 5.2.1 on 2025-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_deposit_related_package_alter_deposit_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
    ]
